//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.19050
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MARTANavigation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MARTANavigation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Navigation.Resources.MARTANavigation", typeof(MARTANavigation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Terms&gt;
        ///  &lt;Term Title=&quot;Process Diagram Library&quot;
        ///        URL=&quot;/Lists/Diagram%20Library/&quot; /&gt;
        ///  &lt;Term Title=&quot;Documents&quot;
        ///        Url=&quot;/Lists/Documents/&quot; /&gt;
        ///  &lt;Term Title=&quot;Proposed Changes&quot;
        ///        URL=&quot;/Lists/Proposed%20Changes/&quot; /&gt;
        ///&lt;/Terms&gt;.
        /// </summary>
        internal static string PlanningTemplate_Global {
            get {
                return ResourceManager.GetString("PlanningTemplate_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Terms&gt;
        ///&lt;/Terms&gt;.
        /// </summary>
        internal static string PlanningTemplate_Local {
            get {
                return ResourceManager.GetString("PlanningTemplate_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Terms&gt;
        ///  &lt;Term Title=&quot;Pages&quot;
        ///        URL=&quot;&quot;&gt;
        ///    &lt;Term Title=&quot;Overview&quot;
        ///          Url=&quot;/Overview.aspx&quot; /&gt;
        ///    &lt;Term Title=&quot;Instructions&quot;
        ///          Url=&quot;/Instructions.aspx&quot; /&gt;
        ///    &lt;Term Title=&quot;Diagrams&quot;
        ///          Url=&quot;/Diagrams.aspx&quot; /&gt;
        ///    &lt;Term Title=&quot;Metrics&quot;
        ///          Url=&quot;/Metrics.aspx&quot; /&gt;
        ///    &lt;Term Title=&quot;Planning&quot;
        ///          Url=&quot;/Planning/default.aspx&quot; /&gt;
        ///  &lt;/Term&gt;
        ///&lt;/Terms&gt;.
        /// </summary>
        internal static string ProcessTemplate_Global {
            get {
                return ResourceManager.GetString("ProcessTemplate_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Terms&gt;
        ///  &lt;Term Title=&quot;Apps&quot;
        ///        URL=&quot;&quot; &gt;
        ///    &lt;Term Title=&quot;Tasks&quot;
        ///          URL=&quot;/Lists/Tasks/&quot; /&gt;
        ///    &lt;Term Title=&quot;Diagram Library&quot;
        ///          URL=&quot;/Lists/Diagram%20Library/&quot; /&gt;
        ///    &lt;Term Title=&quot;Roles and Responsibilities&quot;
        ///          URL=&quot;/Lists/Roles%20and%20Responsibilities/&quot; /&gt;
        ///  &lt;/Term&gt;
        ///&lt;/Terms&gt;.
        /// </summary>
        internal static string ProcessTemplate_Local {
            get {
                return ResourceManager.GetString("ProcessTemplate_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Terms&gt;
        ///  &lt;Term Title=&quot;Pages&quot;
        ///        URL=&quot;&quot;&gt;
        ///    &lt;Term Title=&quot;News&quot;
        ///          Url=&quot;/News.aspx&quot; /&gt;
        ///    &lt;Term Title=&quot;Who We Are&quot;
        ///          Url=&quot;/Who%20We%20Are.aspx&quot; /&gt;
        ///    &lt;Term Title=&quot;What We Do&quot;
        ///          Url=&quot;/What%20We%20Do.aspx&quot; /&gt;
        ///    &lt;Term Title=&quot;Site Directory&quot;
        ///          Url=&quot;/Site%20Directory.aspx&quot; /&gt;
        ///  &lt;/Term&gt;
        ///  &lt;Term Title=&quot;Request a Service&quot;
        ///        Url=&quot;&quot;&gt;
        ///    &lt;Term Title=&quot;Service 1&quot;
        ///          Url=&quot;www.google.com&quot; /&gt;
        ///    &lt;Term Title=&quot;Service 2&quot;
        ///          Url=&quot;www.bing.com&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StorefrontTemplate_Global {
            get {
                return ResourceManager.GetString("StorefrontTemplate_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Terms&gt;
        ///&lt;/Terms&gt;.
        /// </summary>
        internal static string StorefrontTemplate_Local {
            get {
                return ResourceManager.GetString("StorefrontTemplate_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Terms&gt;
        ///  &lt;Term Title=&quot;Pages&quot;
        ///        URL=&quot;&quot;&gt;
        ///    &lt;Term Title=&quot;Metrics&quot; Url=&quot;/Metrics.aspx&quot;&gt;&lt;/Term&gt;
        ///    &lt;Term Title=&quot;Knowledge&quot;
        ///          Url=&quot;/Knowledge.aspx&quot;&gt;&lt;/Term&gt;
        ///  &lt;/Term&gt;
        ///&lt;/Terms&gt;.
        /// </summary>
        internal static string TeamTemplate_Global {
            get {
                return ResourceManager.GetString("TeamTemplate_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Terms&gt;
        ///  &lt;Term Title=&quot;Apps&quot;
        ///        URL=&quot;&quot; &gt;
        ///  &lt;Term Title=&quot;Calendar&quot;
        ///        URL=&quot;/_layouts/15/start.aspx#/Lists/Calendar/&quot; /&gt;
        ///    &lt;Term Title=&quot;Tasks&quot;
        ///          URL=&quot;/_layouts/15/start.aspx#/Lists/Tasks/&quot; /&gt;
        ///    &lt;Term Title=&quot;Documents&quot;
        ///          URL=&quot;/_layouts/15/start.aspx#/Lists/Documents/&quot; /&gt;
        ///    &lt;Term Title=&quot;Contacts&quot;
        ///          URL=&quot;/_layouts/15/start.aspx#/Lists/Contacts/&quot; /&gt;
        ///  &lt;/Term&gt;
        ///&lt;/Terms&gt;.
        /// </summary>
        internal static string TeamTemplate_Local {
            get {
                return ResourceManager.GetString("TeamTemplate_Local", resourceCulture);
            }
        }
    }
}
